Feature/fix project root issues
mapeditor/tiled-to-godot-export pull request #40
Opened 2022-03-26 17:04 UTC by mcarpenter622

2022-03-27 01:12 UTC, MikeMnD approved these changes

2022-03-28 08:27 UTC, bjorn requested changes

2022-03-28 08:27 UTC, bjorn commented on export_to_godot_tilemap.js
> +                let filePath = tileset.asset.fileName.substring(0, slashIndex);
Since you introduced a variable, let's use it where possible:
```suggestion
            let slashIndex = tilesetPath.lastIndexOf("/");
            if(slashIndex >= 0) {
                let filePath = tilesetPath.substring(0, slashIndex);
```
Also, instead of looking for `/`, consider using [`FileInfo.path(tilesetPath)`](https://www.mapeditor.org/docs/scripting/interfaces/FileInfo.html#path). Though it's not clear to me if we need to handle the case where there isn't a `/`. This should actually only happen in case of an embedded tileset, which has an empty filename.

2022-03-28 08:27 UTC, bjorn commented on export_to_godot_tilemap.js
> +                            tilesetPath = object.tile.tileset.image.replace(filePath, this.projectRoot);
```suggestion
                        let slashIndex = tilesetPath.lastIndexOf("/");
                        if(slashIndex >= 0) {
                            let filePath = tilesetPath.substring(0, slashIndex);
                            tilesetPath = tilesetPath.replace(filePath, this.projectRoot);
```
Though again, it seems to me that this should rather be something like:
```js
let tilesetPath = FileInfo.joinPaths(this.projectRoot, FileInfo.fileName(tilesetPath));
```

2022-03-28 08:27 UTC, bjorn commented on export_to_godot_tileset.js
> +        this.filePath = this.tileset.image.substring(0, this.tileset.image.lastIndexOf("/"));
```suggestion
        this.filePath = FileInfo.path(this.tileset.image);
```
But are we sure the file path should be based on the image, rather than `fileName`?

2022-03-28 13:52 UTC, mcarpenter622 commented on export_to_godot_tileset.js
> +        this.filePath = this.tileset.image.substring(0, this.tileset.image.lastIndexOf("/"));
I am positive for this one we should use the tileset.image.  This filepath is being used to update the image path for the tileset, not the tileset itself. Since the image can be in a different folder from the tileset file this can cause issues with the replacement logic.  

IE this is the output that filepath is being used for:
[ext_resource path="res://maps/terrain.png" type="Texture" id=1]

I do like the FileInfo.path suggestion quite a bit though. I didn't realize that existed. I will update the PR to use those functions.

2022-03-28 14:24 UTC, bjorn commented on export_to_godot_tileset.js
> +        this.filePath = this.tileset.image.substring(0, this.tileset.image.lastIndexOf("/"));
> This filepath is being used to update the image path for the tileset, not the tileset itself.

Makes sense, thanks for going into a bit of detail!

> I do like the FileInfo.path suggestion quite a bit though. I didn't realize that existed. I will update the PR to use those functions.

Note that in the [Files view](https://github.com/mapeditor/tiled-to-godot-export/pull/40/files) you can click "Add suggestion to batch" and eventually commit all suggestions you would apply as-is. :-)

2022-03-28 14:38 UTC, mcarpenter622 commented on export_to_godot_tileset.js
> +        this.filePath = this.tileset.image.substring(0, this.tileset.image.lastIndexOf("/"));
Hey @bjorn , I went ahead and made some updates. I was able to clean up the logic quite a bit after your suggestions.

2022-03-28 21:04 UTC, bjorn approved these changes

2022-03-28 21:05 UTC, bjorn commented on export_to_godot_tileset.js
> +        this.filePath = this.tileset.image.substring(0, this.tileset.image.lastIndexOf("/"));
Yeah, that looks much better! 👍 I've approved it now since on JS or Tiled API level I have nothing to add, but I didn't test the change.

2022-03-28 21:12 UTC, mcarpenter622 commented
I tested it pretty thoroughly, but I'll give it another pass and merge it
in a few.

Thanks guys!

On Mon, Mar 28, 2022, 5:06 PM Thorbjørn Lindeijer ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In export_to_godot_tileset.js
> <https://github.com/mapeditor/tiled-to-godot-export/pull/40#discussion_r836850787>
> :
>
> > @@ -6,8 +6,9 @@ class GodotTilesetExporter {
>
>          this.tileset = tileset;
>
>          this.fileName = fileName;
>
>          // noinspection JSUnresolvedFunction
>
> -        this.projectRoot = getResPath(this.tileset.property("projectRoot"), fileName);
>
> -        this.spriteImagePath = this.tileset.image.replace(this.projectRoot, "");
>
> +        this.projectRoot = getResPath(this.tileset.property("projectRoot"), this.tileset.image);
>
> +        this.filePath = this.tileset.image.substring(0, this.tileset.image.lastIndexOf("/"));
>
>
> Yeah, that looks much better! 👍 I've approved it now since on JS or
> Tiled API level I have nothing to add, but I didn't test the change.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mapeditor/tiled-to-godot-export/pull/40#discussion_r836850787>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADJ7PVROOKC3RRM5FUXOV2LVCINLLANCNFSM5RXLH75A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-28 23:11 UTC, merged